package main

var PlanningArea = []string{
	"Ang Mo Kio",
	"Bedok",
	"Bishan",
	"Bukit Batok",
	"Bukit Merah",
	"Bukit Panjang",
	"Bukit Timah",
	"Choa Chu Kang",
	"Clementi",
	"Downtown Core",
	"Geylang",
	"Hougang",
	"Jurong East",
	"Jurong West",
	"Kallang",
	"Mandai",
	"Marine Parade",
	"Museum",
	"Newton",
	"Novena",
	"Orchard",
	"Outram",
	"Pasir Ris",
	"Punggol",
	"Queenstown",
	"River Valley",
	"Rochor",
	"Sembawang",
	"Sengkang",
	"Serangoon",
	"Singapore River",
	"Southern Islands",
	"Tampines",
	"Tanglin",
	"Toa Payoh",
	"Woodlands",
	"Yishun",
}

var MRT = []string{
	"Admiralty",
	"Aljunied",
	"Ang Mo Kio",
	"Bangkit",
	"Bartley",
	"Bayshore (U/C)",
	"Beauty World",
	"Bedok",
	"Bedok North (U/C)",
	"Bedok Reservoir (U/C)",
	"Bencoolen (U/C)",
	"Bishan",
	"Boon Keng",
	"Boon Lay",
	"Botanic Gardens",
	"Bouna Vista",
	"Braddell",
	"Bright Hill (U/C)",
	"Brighthill",
	"Buangkok",
	"Bugis",
	"Bukit Batok",
	"Bukit Gombak",
	"Bukit Panjang",
	"Caldecott",
	"Canberra (U/C)",
	"Cashew",
	"Cheng Lim",
	"Chinatown",
	"Chinese Garden",
	"Choa Chu Kang",
	"Clarke Quay",
	"Clementi",
	"Coral Edge",
	"Cove",
	"Dakota",
	"Dhoby Ghaut",
	"Dover",
	"Downtown",
	"Eunos",
	"Farmway",
	"Farrer Park",
	"Farrer Road",
	"Fernvale",
	"Fort Canning (U/C)",
	"Great World (U/C)",
	"Harbourfront",
	"Havelock (U/C)",
	"Haw Par Villa",
	"Hillview",
	"Holland Village",
	"Hougang",
	"Jalan Besar (U/C)",
	"Kadaloor",
	"Kaki Bukit (U/C)",
	"Kallang",
	"Kangkar",
	"Keat Hong",
	"Kembangan",
	"Kent Ridge",
	"Khatib",
	"King Albert Park",
	"Kovan",
	"Labrador Park",
	"Lakeside",
	"Lavender",
	"Layar",
	"Lentor (U/C)",
	"Little India",
	"Lorong Chuan",
	"Macpherson",
	"Marina Bay",
	"Marine Parade (U/C)",
	"Marine Terrace (U/C)",
	"Marsiling",
	"Marymount",
	"Maxwell (U/C)",
	"Mayflower (U/C)",
	"Mountbatten",
	"Mt Pleasant (U/C)",
	"Napier (U/C)",
	"Newton",
	"Nicoll Highway",
	"Novena",
	"Oasis",
	"One North ",
	"Orchard",
	"Orchard Boulevard (U/C)",
	"Outram Park",
	"Pasir Panjang",
	"Pasir Ris",
	"Paya Lebar",
	"Pending",
	"Phoenix",
	"Potong Pasir",
	"Punggol",
	"Queenstown",
	"Ranggung",
	"Redhill",
	"Rochor",
	"Rumbia",
	"Segar",
	"Sembawang",
	"Sengkang",
	"Serangoon",
	"Shenton Way (U/C)",
	"Simei",
	"Sin Ming (U/C)",
	"Sixth Avenue",
	"Somerset",
	"Soo Teck (U/C)",
	"Springleaf (U/C)",
	"Stadium",
	"Stevens",
	"Tampines",
	"Tampines East (U/C)",
	"Tan Kah Kee",
	"Tanah Merah",
	"Tanjong Katong (U/C)",
	"Tanjong Pagar",
	"Teck Whye",
	"Telok Ayer",
	"Telok Blangah",
	"Telok Kurau (U/C)",
	"Ten Mile Junction",
	"Thanggam",
	"Tiong Bahru",
	"Toa Payoh",
	"Ubi (U/C)",
	"Upper Changi (U/C)",
	"Upper Thomson (U/C)",
	"Woodlands",
	"Woodlands South (U/C)",
	"Woodleigh",
	"Yew Tee",
	"Yio Chu Kang",
	"Yishun",
}
